/**
 * Clear Sky Chart Time Synchronization Module
 * 
 * Handles the complex timing logic for Clear Sky Charts:
 * 1. Charts are generated at specific times and represent future forecasts
 * 2. First column represents the hour when the chart was generated
 * 3. Need to map chart columns to actual times based on generation time
 * 4. Handle dynamic observing windows based on current time vs sunset/sunrise
 */

import { LocationConfig } from '@/types/observation';
import { calculateSunTimes, calculateObservingWindow, formatTime } from './astronomical-calculations';

export interface ChartTimeMapping {
  generatedAt: Date;
  firstColumnTime: Date;
  columnHours: Date[];
  chartAgeHours: number;
}

export interface DynamicObservingWindow {
  start: Date;
  end: Date;
  totalHours: number;
  isPartialNight: boolean;
  reason: string;
}

/**
 * Determine when a Clear Sky Chart was generated by fetching the HTML page and parsing "last updated" time
 * The first column of the chart represents the hour when it was last updated
 */
export async function inferChartGenerationTime(chartUrl: string): Promise<ChartTimeMapping> {
  try {
    // Extract chart ID from any valid Clear Sky Chart URL
    const chartId = extractChartId(chartUrl);
    
    // Construct HTML page URL to get last updated time
    const htmlUrl = `https://www.cleardarksky.com/c/${chartId}key.html`;
    
    console.log(`[Chart Time Sync] Fetching chart metadata from: ${htmlUrl}`);
    
    // Fetch the HTML page
    const response = await fetch(htmlUrl);
    if (!response.ok) {
      throw new Error(`Failed to fetch chart HTML: ${response.status} ${response.statusText}`);
    }
    
    const htmlContent = await response.text();
    
    // Parse the "last updated" time from HTML
    const lastUpdatedTime = parseLastUpdatedTime(htmlContent);
    
    if (!lastUpdatedTime) {
      throw new Error('Could not parse last updated time from chart HTML');
    }
    
    console.log(`[Chart Time Sync] Chart last updated: ${lastUpdatedTime.toISOString()}`);
    
    // The first column hour is the last updated hour
    const firstColumnTime = new Date(lastUpdatedTime);
    const currentTime = new Date();
    const chartAgeHours = (currentTime.getTime() - lastUpdatedTime.getTime()) / (1000 * 60 * 60);
    
    // Generate array of times for each column (48 hours of forecast)
    const columnHours: Date[] = [];
    for (let i = 0; i < 48; i++) {
      const columnTime = new Date(firstColumnTime.getTime() + (i * 60 * 60 * 1000));
      columnHours.push(columnTime);
    }
    
    return {
      generatedAt: lastUpdatedTime,
      firstColumnTime: firstColumnTime,
      columnHours: columnHours,
      chartAgeHours: Math.round(chartAgeHours * 10) / 10
    };
    
  } catch (error) {
    console.error(`[Chart Time Sync] Failed to parse chart timing: ${error}`);
    throw new Error(`Chart time synchronization failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

/**
 * Extract chart ID from any Clear Sky Chart URL format
 */
function extractChartId(url: string): string {
  // Handle various URL formats:
  // https://www.cleardarksky.com/c/FourPksObWAkey.html
  // https://www.cleardarksky.com/c/FourPksObWAcsk.gif
  // https://www.cleardarksky.com/c/FourPksObWA.html (legacy)
  
  const patterns = [
    /\/c\/([^\/]+)key\.html/,    // ...FourPksObWAkey.html
    /\/c\/([^\/\?]+)csk\.gif/,   // ...FourPksObWAcsk.gif
    /\/c\/([^\/]+)\.html/        // ...FourPksObWA.html (legacy)
  ];
  
  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) {
      let chartId = match[1];
      // Remove 'key' suffix if present
      chartId = chartId.replace(/key$/, '');
      console.log(`[Chart ID] Extracted: ${chartId} from ${url}`);
      return chartId;
    }
  }
  
  throw new Error(`Invalid Clear Sky Chart URL format: ${url}`);
}

/**
 * Parse the "last updated" time from Clear Sky Chart HTML page
 */
function parseLastUpdatedTime(htmlContent: string): Date | null {
  console.log(`[HTML Parser] Analyzing HTML content (${htmlContent.length} chars)`);
  
  // Log first 2000 characters to see what we're working with
  console.log(`[HTML Parser] HTML sample:`, htmlContent.substring(0, 2000));
  
  // Look for patterns like:
  // "Last updated: 2025-10-18 14:00 PDT"
  // "Updated: Oct 18, 2025 2:00 PM PDT"  
  // "Generated: 2025/10/18 14:00 UTC-7"
  // Also try more flexible patterns
  
  const patterns = [
    /Last updated:\s*(\d{4}-\d{2}-\d{2})\s+(\d{1,2}):(\d{2})\s+([A-Z]{3,4})/i,
    /Updated:\s*([A-Za-z]{3})\s+(\d{1,2}),\s+(\d{4})\s+(\d{1,2}):(\d{2})\s+([AP]M)\s+([A-Z]{3,4})/i,
    /Generated:\s*(\d{4})\/(\d{2})\/(\d{2})\s+(\d{1,2}):(\d{2})\s+UTC([+-]\d+)/i,
    // Add more flexible patterns
    /last\s+updated[:\s]*(\d{4}[-\/]\d{2}[-\/]\d{2})[^\d]*(\d{1,2}):(\d{2})/i,
    /updated[:\s]*(\d{4}[-\/]\d{2}[-\/]\d{2})[^\d]*(\d{1,2}):(\d{2})/i,
    // Look for any date-time pattern
    /(\d{4}[-\/]\d{2}[-\/]\d{2})[^\d]*(\d{1,2}):(\d{2})/
  ];
  
  for (let i = 0; i < patterns.length; i++) {
    const pattern = patterns[i];
    const match = htmlContent.match(pattern);
    if (match) {
      console.log(`[HTML Parser] Pattern ${i} matched:`, match[0]);
      try {
        const parsedDate = parseMatchedDateTime(match, pattern);
        if (parsedDate) {
          console.log(`[HTML Parser] Successfully parsed: ${parsedDate.toISOString()}`);
          return parsedDate;
        }
      } catch (error) {
        console.warn(`[HTML Parser] Failed to parse date match ${i}: ${error}`);
        continue;
      }
    } else {
      console.log(`[HTML Parser] Pattern ${i} did not match`);
    }
  }
  
  console.error('[HTML Parser] No valid last updated time pattern found in HTML');
  console.log('[HTML Parser] HTML content includes these time-related keywords:', 
    htmlContent.match(/\b(updated|generated|last|time|hour|chart)\b/gi) || 'none found');
  
  return null;
}

/**
 * Parse matched date/time pattern into Date object
 */
function parseMatchedDateTime(match: RegExpMatchArray, pattern: RegExp): Date | null {
  const patternStr = pattern.toString();
  
  console.log(`[DateTime Parser] Processing pattern: ${patternStr.substring(0, 50)}...`);
  console.log(`[DateTime Parser] Match groups:`, match.slice(1));
  
  if (patternStr.includes('Last updated')) {
    // Pattern: "Last updated: 2025-10-18 14:00 PDT"
    const [, dateStr, hourStr, minuteStr, timezone] = match;
    const date = new Date(`${dateStr}T${hourStr.padStart(2, '0')}:${minuteStr}:00`);
    return adjustForTimezone(date, timezone);
  }
  
  if (patternStr.includes('Updated') && patternStr.includes('[A-Za-z]')) {
    // Pattern: "Updated: Oct 18, 2025 2:00 PM PDT"
    const [, month, day, year, hour, minute, ampm, timezone] = match;
    const hour24 = convert12to24Hour(parseInt(hour), ampm);
    const monthNum = parseMonth(month);
    const date = new Date(parseInt(year), monthNum - 1, parseInt(day), hour24, parseInt(minute));
    return adjustForTimezone(date, timezone);
  }
  
  if (patternStr.includes('Generated')) {
    // Pattern: "Generated: 2025/10/18 14:00 UTC-7"
    const [, year, month, day, hour, minute, utcOffset] = match;
    const date = new Date(parseInt(year), parseInt(month) - 1, parseInt(day), parseInt(hour), parseInt(minute));
    const offsetHours = parseInt(utcOffset);
    // Adjust for UTC offset
    return new Date(date.getTime() - (offsetHours * 60 * 60 * 1000));
  }
  
  // Handle flexible patterns - try to extract date and time
  if (match.length >= 3) {
    const [, dateStr, hourStr, minuteStr] = match;
    
    try {
      // Parse flexible date format (YYYY-MM-DD or YYYY/MM/DD)
      const dateParts = dateStr.split(/[-\/]/);
      if (dateParts.length === 3) {
        const year = parseInt(dateParts[0]);
        const month = parseInt(dateParts[1]) - 1; // JS months are 0-based
        const day = parseInt(dateParts[2]);
        
        const hour = parseInt(hourStr);
        const minute = parseInt(minuteStr || '0');
        
        const date = new Date(year, month, day, hour, minute);
        
        // Assume local timezone for flexible patterns
        console.log(`[DateTime Parser] Flexible pattern created date: ${date.toISOString()}`);
        return date;
      }
    } catch (error) {
      console.warn(`[DateTime Parser] Failed to parse flexible pattern: ${error}`);
    }
  }
  
  return null;
}

/**
 * Convert 12-hour time to 24-hour time
 */
function convert12to24Hour(hour: number, ampm: string): number {
  if (ampm.toUpperCase() === 'AM') {
    return hour === 12 ? 0 : hour;
  } else {
    return hour === 12 ? 12 : hour + 12;
  }
}

/**
 * Parse month abbreviation to number
 */
function parseMonth(monthStr: string): number {
  const months = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12
  };
  return months[monthStr as keyof typeof months] || 1;
}

/**
 * Adjust date for timezone (simplified - assumes common US timezones)
 */
function adjustForTimezone(date: Date, timezone: string): Date {
  // This is a simplified timezone adjustment
  // In production, you'd want to use a proper timezone library
  const offsets: { [key: string]: number } = {
    'PDT': -7, 'PST': -8,  // Pacific
    'MDT': -6, 'MST': -7,  // Mountain  
    'CDT': -5, 'CST': -6,  // Central
    'EDT': -4, 'EST': -5   // Eastern
  };
  
  const offset = offsets[timezone.toUpperCase()];
  if (offset !== undefined) {
    // Adjust from local time to UTC, then to the specified timezone
    return new Date(date.getTime() - (offset * 60 * 60 * 1000));
  }
  
  return date; // Return as-is if timezone not recognized
}

/**
 * Legacy function signature for backwards compatibility - now async
 */

/**
 * Calculate observing window based on current time and astronomical data
 * Handles three scenarios:
 * 1. Before sunset: Full night ahead (sunset+1hr to sunrise-1hr)
 * 2. After sunset, before sunrise: Rest of current night
 * 3. After sunrise: Next night
 */
export function calculateDynamicObservingWindow(
  currentTime: Date,
  location: LocationConfig,
  startOffset: number = 60,
  endOffset: number = 60
): DynamicObservingWindow {
  const today = new Date(currentTime);
  const tomorrow = new Date(currentTime);
  tomorrow.setDate(tomorrow.getDate() + 1);
  
  // Calculate sun times for today and tomorrow
  const todaySun = calculateSunTimes(today, location);
  const tomorrowSun = calculateSunTimes(tomorrow, location);
  
  // Determine which scenario we're in
  if (currentTime < todaySun.sunset) {
    // Scenario 1: Before sunset - plan for tonight
    const window = calculateObservingWindow(todaySun, startOffset, endOffset);
    return {
      start: window.start,
      end: window.end,
      totalHours: window.totalHours,
      isPartialNight: false,
      reason: `Full night observing window: ${formatTime(window.start)} to ${formatTime(window.end)}`
    };
  } else if (currentTime < todaySun.sunrise) {
    // Scenario 2: After sunset, before sunrise - rest of current night
    const observingStart = new Date(Math.max(currentTime.getTime(), todaySun.sunset.getTime() + startOffset * 60000));
    const observingEnd = new Date(todaySun.sunrise.getTime() - endOffset * 60000);
    
    // Handle case where sunrise is tomorrow
    if (observingEnd < observingStart) {
      observingEnd.setDate(observingEnd.getDate() + 1);
    }
    
    const totalHours = Math.max(0, (observingEnd.getTime() - observingStart.getTime()) / (1000 * 60 * 60));
    
    return {
      start: observingStart,
      end: observingEnd,
      totalHours: Math.round(totalHours * 10) / 10,
      isPartialNight: true,
      reason: `Remaining observing time tonight: ${formatTime(observingStart)} to ${formatTime(observingEnd)}`
    };
  } else {
    // Scenario 3: After sunrise - plan for next night
    const window = calculateObservingWindow(tomorrowSun, startOffset, endOffset);
    return {
      start: window.start,
      end: window.end,
      totalHours: window.totalHours,
      isPartialNight: false,
      reason: `Next night observing window: ${formatTime(window.start)} to ${formatTime(window.end)}`
    };
  }
}

/**
 * Map Clear Sky Chart columns to specific hours for filtering
 * Returns which columns correspond to the observing window
 */
export function mapObservingWindowToChartColumns(
  observingWindow: DynamicObservingWindow,
  chartTiming: ChartTimeMapping
): { columnIndices: number[]; hours: Date[] } {
  const columnIndices: number[] = [];
  const hours: Date[] = [];
  
  chartTiming.columnHours.forEach((columnTime, index) => {
    // Check if this column's hour falls within our observing window
    if (columnTime >= observingWindow.start && columnTime <= observingWindow.end) {
      columnIndices.push(index);
      hours.push(columnTime);
    }
  });
  
  return { columnIndices, hours };
}

/**
 * Get user-friendly description of the forecast timing
 */
export function getTimingDescription(
  observingWindow: DynamicObservingWindow,
  chartTiming: ChartTimeMapping,
  relevantColumns: number
): string {
  const currentTime = new Date();
  const hoursUntilStart = (observingWindow.start.getTime() - currentTime.getTime()) / (1000 * 60 * 60);
  const chartAge = Math.round(chartTiming.chartAgeHours * 10) / 10;
  
  let description = observingWindow.reason;
  
  if (hoursUntilStart > 0) {
    description += ` (starts in ${Math.round(hoursUntilStart * 10) / 10} hours)`;
  } else if (hoursUntilStart > -1) {
    description += ` (starting now)`;
  }
  
  description += `. Forecast based on ${relevantColumns} hours of Clear Sky Chart data`;
  
  if (chartAge > 6) {
    description += ` (chart is ${chartAge} hours old - may be less accurate)`;
  }
  
  return description;
}

/**
 * Check if we have enough chart data to cover the observing window
 */
export function validateChartCoverage(
  observingWindow: DynamicObservingWindow,
  chartTiming: ChartTimeMapping
): { adequate: boolean; missingHours: number; warning?: string } {
  const windowEnd = observingWindow.end;
  const chartEnd = chartTiming.columnHours[chartTiming.columnHours.length - 1];
  
  if (windowEnd <= chartEnd) {
    return { adequate: true, missingHours: 0 };
  }
  
  const missingHours = (windowEnd.getTime() - chartEnd.getTime()) / (1000 * 60 * 60);
  const warning = `Chart only covers ${Math.round((chartEnd.getTime() - observingWindow.start.getTime()) / (1000 * 60 * 60) * 10) / 10} of ${observingWindow.totalHours} observing hours`;
  
  return {
    adequate: false,
    missingHours: Math.round(missingHours * 10) / 10,
    warning
  };
}
