import { NextRequest, NextResponse } from 'next/server';
import { calculateSunTimes, calculateObservingWindow, formatTime, calculateMoonData } from '@/lib/astronomical-calculations';
import { fetchClearSkyChartData } from '@/lib/clear-sky-parser';
import { evaluateObservingCondition } from '@/lib/observation-evaluator';
import fs from 'fs';
import path from 'path';

interface ObservationCriteria {
  location: {
    name: string;
    latitude: number;
    longitude: number;
    timezone: string;
    clearSkyChartUrl: string;
    clearSkyChartImageUrl?: string; // Optional for backward compatibility
  };
  observingWindow: {
    startOffset: number;
    endOffset: number;
  };
}

interface TimeWindow {
  start: string;
  end: string;
  quality: "excellent" | "good" | "dubious" | "poor";
  reason: string;
  count?: number;
}

interface ObservingWindowData {
  start: Date;
  end: Date;
  totalHours: number;
}

// Helper function to calculate end time for a time window
function calculateEndTime(startTime: string): string {
  const [hours] = startTime.split(':').map(Number);
  const endHour = (hours + 1) % 24;
  return `${endHour.toString().padStart(2, '0')}:00`;
}

// Enhanced email formatting function
function formatEmailContent(
  overallRating: string, 
  timeWindows: TimeWindow[], 
  observingWindow: ObservingWindowData, 
  sunTimes: { sunset: Date; sunrise: Date }, 
  moonData: { phase?: number; illumination?: number; rise?: Date; set?: Date },
  summary: string,
  location: string
): string {
  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const getStatusEmoji = (status: string) => {
    switch (status) {
      case 'excellent': return '⭐ EXCELLENT';
      case 'good': return '👍 GOOD';
      case 'dubious': return '⚠️ DUBIOUS';
      case 'poor': return '❌ POOR';
      default: return '❓ UNKNOWN';
    }
  };

  const getQualityEmoji = (quality: string) => {
    switch (quality) {
      case 'excellent': return '⭐';
      case 'good': return '👍';
      case 'dubious': return '⚠️';
      case 'poor': return '❌';
      default: return '❓';
    }
  };

  let timeWindowsText = '';
  if (timeWindows.length > 0) {
    timeWindowsText = timeWindows.map(window => {
      const duration = window.count || 1;
      const durationText = duration === 1 ? '1 hour' : `${duration} hours`;
      return `${getQualityEmoji(window.quality)} ${window.start} - ${window.end} (${durationText}): ${window.quality.toUpperCase()}
   ${window.reason}`;
    }).join('\n\n');
  } else {
    timeWindowsText = 'No observing conditions data available.';
  }

  const moonPhaseText = moonData.phase !== undefined 
    ? `${(moonData.phase * 100).toFixed(0)}%` 
    : 'Unknown';
  const moonIllumination = moonData.illumination !== undefined 
    ? `${(moonData.illumination * 100).toFixed(0)}%` 
    : 'Unknown';

  return `🌟 MAPLE VALLEY OBSERVATORY DAILY OBSERVATION REPORT
${date}

OVERALL ASSESSMENT: ${getStatusEmoji(overallRating)}

OBSERVING WINDOW: ${formatTime(observingWindow.start)} to ${formatTime(observingWindow.end)}
Total observing time: ${observingWindow.totalHours} hours

SUN TIMES:
🌅 Sunset: ${formatTime(sunTimes.sunset)}
🌄 Sunrise: ${formatTime(sunTimes.sunrise)}

MOON CONDITIONS:
🌙 Phase: ${moonPhaseText} illuminated
💡 Brightness: ${moonIllumination}
🌅 Rise: ${moonData.rise ? formatTime(moonData.rise) : 'N/A'}
🌇 Set: ${moonData.set ? formatTime(moonData.set) : 'N/A'}

TONIGHT'S CONDITIONS BY TIME:

${timeWindowsText}

SUMMARY:
${summary}

LOCATION: ${location}

---
This automated report was generated by the Four Peaks Observatory observation forecast system.
For real-time conditions, visit the Clear Sky Chart: https://www.cleardarksky.com/c/FourPksObWAkey.html

Clear skies!
🔭 Four Peaks Observatory`;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { 
      recipient = process.env.DAILY_REPORT_EMAIL, 
      formspreeId = process.env.FORMSPREE_FORM_ID, 
      triggerSource = 'manual' 
    } = body;

    // Validate required parameters
    if (!recipient || !formspreeId) {
      return NextResponse.json(
        { 
          success: false, 
          error: 'Missing required parameters: recipient and formspreeId',
          hint: 'Set FORMSPREE_FORM_ID and DAILY_REPORT_EMAIL in environment variables or pass in request body'
        },
        { status: 400 }
      );
    }

    // Load observation criteria
    const configPath = path.join(process.cwd(), 'src/config/observation-criteria.json');
    const configData = fs.readFileSync(configPath, 'utf8');
    const criteria: ObservationCriteria = JSON.parse(configData);

    const today = new Date();

    // Calculate sun times and observing window
    const locationConfig = {
      ...criteria.location,
      clearSkyChartImageUrl: criteria.location.clearSkyChartImageUrl || criteria.location.clearSkyChartUrl.replace('.html', 'csk.gif')
    };
    const sunTimes = calculateSunTimes(today, locationConfig);
    const observingWindow = calculateObservingWindow(
      sunTimes,
      criteria.observingWindow.startOffset,
      criteria.observingWindow.endOffset
    );

    // Get moon data
    const moonData = await calculateMoonData(today, locationConfig);

    // Fetch Clear Sky Chart data
    const chartData = await fetchClearSkyChartData(criteria.location.clearSkyChartUrl);

    // Process conditions for the observing window
    const conditions = chartData.forecast.map(condition => {
      const evaluation = evaluateObservingCondition(condition);
      
      return {
        time: condition.time,
        quality: evaluation.overall,
        reason: evaluation.reason,
        cloudCover: condition.cloudCover,
        transparency: condition.transparency,
        seeing: condition.seeing
      };
    });

    // Filter conditions to observing window
    const filteredConditions = conditions.filter(condition => {
      const [hours] = condition.time.split(':').map(Number);
      
      const conditionTimeToday = new Date(today);
      conditionTimeToday.setHours(hours, 0, 0, 0);
      
      const conditionTimeTomorrow = new Date(today);
      conditionTimeTomorrow.setDate(conditionTimeTomorrow.getDate() + 1);
      conditionTimeTomorrow.setHours(hours, 0, 0, 0);
      
      const conditionEndToday = new Date(conditionTimeToday);
      conditionEndToday.setHours(hours + 1, 0, 0, 0);
      
      const conditionEndTomorrow = new Date(conditionTimeTomorrow);
      conditionEndTomorrow.setHours(hours + 1, 0, 0, 0);
      
      const overlapToday = (conditionTimeToday < observingWindow.end) && (conditionEndToday > observingWindow.start);
      const overlapTomorrow = (conditionTimeTomorrow < observingWindow.end) && (conditionEndTomorrow > observingWindow.start);
      
      return overlapToday || overlapTomorrow;
    });

    // Sort conditions for nighttime observing chronology
    // Evening hours (18, 19, 20, 21, 22, 23) come before early morning hours (0, 1, 2, 3, 4, 5)
    filteredConditions.sort((a, b) => {
      const hourA = parseInt(a.time.split(':')[0]);
      const hourB = parseInt(b.time.split(':')[0]);
      
      // Convert hours to observing sequence order
      // Evening hours (18-23) get priority, then early morning hours (0-11)
      const getObservingOrder = (hour: number) => {
        if (hour >= 18) return hour - 18; // 18->0, 19->1, 20->2, 21->3, 22->4, 23->5
        if (hour <= 11) return hour + 6;  // 0->6, 1->7, 2->8, 3->9, 4->10, 5->11
        return hour + 12; // Afternoon hours (12-17) go last: 12->24, 13->25, etc.
      };
      
      return getObservingOrder(hourA) - getObservingOrder(hourB);
    });

    // Group consecutive conditions with proper time ranges
    const timeWindows: TimeWindow[] = [];
    let currentWindow: TimeWindow | null = null;
    
    for (let i = 0; i < filteredConditions.length; i++) {
      const condition = filteredConditions[i];
      
      if (!currentWindow || currentWindow.quality !== condition.quality) {
        if (currentWindow) {
          timeWindows.push(currentWindow);
        }
        currentWindow = {
          start: condition.time,
          end: calculateEndTime(condition.time),
          quality: condition.quality,
          reason: condition.reason,
          count: 1
        };
      } else {
        // Extend the current window
        currentWindow.end = calculateEndTime(condition.time);
        currentWindow.count = (currentWindow.count || 0) + 1;
      }
    }
    
    if (currentWindow) {
      timeWindows.push(currentWindow);
    }

    // Determine overall rating
    let overallRating: 'excellent' | 'good' | 'dubious' | 'poor' = 'poor';
    if (timeWindows.length > 0) {
      const excellentHours = timeWindows.filter(w => w.quality === 'excellent').reduce((sum, w) => sum + (w.count || 1), 0);
      const goodHours = timeWindows.filter(w => w.quality === 'good').reduce((sum, w) => sum + (w.count || 1), 0);
      const totalHours = timeWindows.reduce((sum, w) => sum + (w.count || 1), 0);
      
      const goodRatio = (excellentHours + goodHours) / totalHours;
      
      if (excellentHours >= totalHours * 0.6) {
        overallRating = 'excellent';
      } else if (goodRatio >= 0.6) {
        overallRating = 'good';
      } else if (goodRatio >= 0.3) {
        overallRating = 'dubious';
      }
    }

    // Generate summary
    let summary = '';
    const totalHours = observingWindow.totalHours;
    const bestWindow = timeWindows.find(w => w.quality === 'excellent') || timeWindows.find(w => w.quality === 'good');
    
    if (!bestWindow) {
      summary = `Poor observing conditions throughout the ${totalHours}-hour window. Not recommended for observation tonight.`;
    } else {
      const bestHours = timeWindows.filter(w => w.quality === bestWindow.quality).reduce((sum, w) => sum + (w.count || 1), 0);
      summary = `${bestWindow.quality.charAt(0).toUpperCase() + bestWindow.quality.slice(1)} observing conditions expected during ${bestHours} hour(s) of the ${totalHours}-hour window.`;
      
      if (bestWindow.quality === 'excellent' || bestWindow.quality === 'good') {
        summary += ` Best time: ${bestWindow.start} to ${bestWindow.end}.`;
      }
    }

    // Add moon impact to summary
    if (moonData.illumination && moonData.illumination > 0.8) {
      summary += ` Bright moon (${(moonData.illumination * 100).toFixed(0)}% illuminated) will wash out faint deep sky objects.`;
    }

    // Format email content
    const emailSubject = `🔭 Observatory Report ${new Date().toLocaleDateString()} - ${overallRating.toUpperCase()}`;
    const emailBody = formatEmailContent(
      overallRating,
      timeWindows,
      observingWindow,
      sunTimes,
      {
        phase: moonData.phase,
        illumination: moonData.illumination,
        rise: moonData.rise || undefined,
        set: moonData.set || undefined
      },
      summary,
      criteria.location.name
    );

    // Send email via Formspree
    const formspreeResponse = await fetch(`https://formspree.io/f/${formspreeId}`, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        email: recipient,
        subject: emailSubject,
        message: emailBody,
        _replyto: recipient,
        _subject: emailSubject,
        _autoresponse: false,
        _source: triggerSource,
        _timestamp: new Date().toISOString()
      })
    });

    if (!formspreeResponse.ok) {
      const errorData = await formspreeResponse.text();
      console.error('Formspree error:', errorData);
      return NextResponse.json(
        { 
          success: false, 
          error: 'Failed to send email via Formspree',
          details: errorData
        },
        { status: 500 }
      );
    }

    const formspreeResult = await formspreeResponse.json();

    return NextResponse.json({
      success: true,
      message: 'Daily observation report sent successfully',
      recipient,
      timestamp: new Date().toISOString(),
      triggerSource,
      emailData: {
        subject: emailSubject,
        overallRating,
        timeWindows: timeWindows.length,
        observingHours: totalHours
      },
      formspreeResponse: formspreeResult
    });

  } catch (error) {
    console.error('Error sending daily report:', error);
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to generate or send daily observation report',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}
