// File location mappings for asset manager
const fileLocationMappings: Record<string, string> = {
  'hubble and me.jpg': 'planets',
  '20 day old moon.jpg': 'lunar',
  'crescent moon.jpg': 'lunar',
  'full moon.jpg': 'lunar',
  'twilight moon - copernicus.jpg': 'lunar',
  'twilight moon - tycho region.jpg': 'lunar',
  'twilight moon.jpg': 'lunar',
  'sun .jpg': 'solar',
  'sun.jpg': 'solar',
  'm103.jpg': 'starClusters',
  'm13-1.jpg': 'starClusters',
  'm39.jpg': 'starClusters',
  'm45 - pleiades.jpg': 'starClusters',
  'm45 --1.jpg': 'starClusters',
  'm56.jpg': 'starClusters',
  'm71.jpg': 'starClusters',
  'm92.jpg': 'starClusters',
  'ngc869 and ngc884 - the double cluster.jpg': 'starClusters',
  'double cluster.jpg': 'starClusters',
  'm31-25x300sec-tight-1600x1131.jpg': 'galaxies',
  'm31-final.jpg': 'galaxies',
  'm31.jpg': 'galaxies',
  'm33 - the triangulum galaxy.jpg': 'galaxies',
  'm33-1.jpg': 'galaxies',
  'the leo trio.jpg': 'galaxies',
  'ngc 7635 - m52.jpg': 'wideField',
  'orion-wide-death-valley.jpg': 'wideField',
  'sadr region.jpg': 'wideField',
  'ngc6635-hubble-1.jpg': 'nebulas',
  'ngc7000 and ic5070-2.jpg': 'wideField',
  'cocoon nebula tight.jpg': 'nebulas',
  'cocoon nebula wide.jpg': 'nebulas',
  'crescent nebula.jpg': 'nebulas',
  'heart nebula.jpg': 'nebulas',
  'heart and soul nebulas-4.jpg': 'wideField',
  'ic1396-the elephant.jpg': 'nebulas',
  'ic434.jpg': 'nebulas',
  'ic63.jpg': 'nebulas',
  'm1 - the crab nebula.jpg': 'nebulas',
  'm1.jpg': 'nebulas',
  'm13-4.jpg': 'nebulas',
  'm16.jpg': 'nebulas',
  'm27-2-1.jpg': 'nebulas',
  'm27.jpg': 'nebulas',
  'm42 the orion nebula.jpg': 'nebulas',
  'm97.jpg': 'nebulas',
  'ngc1499.jpg': 'nebulas',
  'ngc2244.jpg': 'nebulas',
  'ngc2264.jpg': 'nebulas',
  'ngc281.jpg': 'nebulas',
  'ngc7000.jpg': 'nebulas',
  'ngc7635 - the bubble nebula - tight.jpg': 'nebulas',
  'ngc7635 - the bubble nebula-wide.jpg': 'nebulas',
  'north america and the pelican.jpg': 'wideField',
  'sh2-132-the-lobsterclaw.jpg': 'nebulas',
  'the soul nebula.jpg': 'nebulas',
  "thor's helmet.jpg": 'nebulas',
  'veil nebula complex.jpg': 'wideField',
  'wizard-lr-pi.jpg': 'nebulas',
  '2017 total eclipse1.jpg': 'events',
  '2017 total eclipse10.jpg': 'events',
  '2017 total eclipse2.mp4': 'events',
  '2017 total eclipse8.jpg': 'events',
  '2017 total eclipse87.jpg': 'events',
  '2017 total eclipse88.jpg': 'events',
  '2017 total eclipse9.jpg': 'events',
  'eclipse2017.jpg': 'events',
};

export default fileLocationMappings;
